### ISSUE TITLE
Issues with Java building

### ISSUE THREAD

**Issue by qdot** [libnifalcon/libnifalcon#15]
From email:

With the example JNIFalconCubeTest, I copied from /libnifalcon/build/lang/swig/ to /libnifalcon/lang/examples/java/JNIFalconCubeTest/ the files:

FalconDeviceBridge.java
FalconVec3d.java
JNIFalcon.java
JNIFalconJNI.java

And compile with:

javac JNIFalconCubeTest.java
java JNIFalconCubeTest

but show:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no JNIFalcon in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1734)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1028)
    at JNIFalconCubeTest.<clinit>(JNIFalconCubeTest.java:4)
Could not find the main class: JNIFalconCubeTest.  Program will exit.

Then I read forums and changed JNIFaclconCubeTest.java in the line 4 to:

System.load("/libnifalcon/build/lib/libJNIFalcon.so");

Next, i got the following error: 

Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/alejo/libnifalcon/build/lib/libJNIFalcon.so: libmawt.so: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1803)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1699)
    at java.lang.Runtime.load0(Runtime.java:770)
    at java.lang.System.load(System.java:1003)
    at JNIFalconCubeTest.<clinit>(JNIFalconCubeTest.java:4)
Could not find the main class: JNIFalconCubeTest.  Program will exit.

**Comment by sjtosco** [comment]
Hi!. You can add JAVA_HOME variable in .bashrc. The commmand is like:

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

Regards!
